# Generated by Django 2.1.2 on 2019-07-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', 'update_core_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verifiedOver13',
            field=models.BooleanField(default=False),
        ),
    ]
