# Generated by Django 2.1.2 on 2019-07-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_user_verifiedover13'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verifiedOver13',
        ),
    ]
