version: '3'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}
  search_data_dev: {}

services:
  postgres:
    build: ./deploy/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=driftr

  search:
    image: elasticsearch:6.7.1
#    volumes:
#      - search_data_dev:/usr/share/elasticsearch/data
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    depends_on:
      - postgres
    links:
      - postgres
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

  web:
    build:
      context: .
      dockerfile: ./deploy/api/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - search
    environment:
      - POSTGRES_USER=driftr
      - USE_DOCKER=yes
      - DJANGO_CONFIGURATION=Local
    volumes:
      - .:/app
      - /dev/shm:/dev/shm
    ports:
      - "8000:8000"
    links:
      - postgres
      - search