# Generated by Django 2.1.2 on 2018-11-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', 'populate_age_ranges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='age_range',
            new_name='age_ranges',
        ),
    ]
