# Generated by Django 2.1.2 on 2019-01-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', 'populate_repeat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportoptions',
            name='detail',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
