# Generated by Django 2.1.2 on 2018-11-13 19:56

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_auto_20181105_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
