# Generated by Django 2.1.2 on 2019-01-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='category',
        ),
        migrations.AddField(
            model_name='activity',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='activities.Category'),
        ),
    ]
