# Generated by Django 2.1.2 on 2018-10-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='activity'),
        ),
    ]
