# Generated by Django 2.1.2 on 2019-02-10 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_auto_20190210_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='recurrence',
        ),
        migrations.AddField(
            model_name='activity',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='activities.Schedule'),
        ),
    ]
