# Generated by Django 2.1.2 on 2019-01-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20190115_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.RemoveField(
            model_name='location',
            name='province',
        ),
        migrations.RemoveField(
            model_name='location',
            name='region',
        ),
    ]
