# Generated by Django 2.1.2 on 2019-02-10 03:28

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20190210_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
    ]
