# Generated by Django 2.1.2 on 2019-07-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_recurrence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='recurrence',
        ),
    ]
