# Generated by Django 2.1.2 on 2019-02-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='activities'),
        ),
    ]
