# Generated by Django 2.1.2 on 2019-07-17 20:54

from django.db import migrations, models
import scheduling.models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_remove_activity_recurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='repeat',
            field=scheduling.models.ChoiceTextField(blank=True, choices=[('RRULE:FREQ=DAILY', 'Daily'), ('RRULE:FREQ=WEEKLY', 'Weekly'), ('RRULE:FREQ=MONTHLY', 'Monthly'), ('RRULE:FREQ=YEARLY', 'Yearly')], default=''),
        ),
    ]
