# Generated by Django 2.1.2 on 2019-03-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='repeat',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='RepeatOptions',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
