# Generated by Django 2.1.2 on 2019-06-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_auto_20190612_2045'),
        ('activities', '0006_auto_20190423_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='allowed_groups', to='friends.Group'),
        ),
    ]
