# Generated by Django 2.1.2 on 2019-09-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20190806_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='is_nsfw',
            new_name='kid_friendly',
        ),
    ]
