# Generated by Django 2.1.2 on 2019-09-09 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_activity_kid_friendly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=10)),
                ('decimal_digits', models.IntegerField(default=2)),
                ('decimal_separator', models.CharField(max_length=1)),
                ('thousands_separator', models.CharField(max_length=1)),
                ('space_symbol', models.BooleanField(default=False)),
                ('symbol_left', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='price',
            new_name='maximum_price',
        ),
        migrations.AddField(
            model_name='activity',
            name='minimum_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='activities.Currency'),
        ),
    ]
