# Generated by Django 2.1.1 on 2018-09-30 01:52
from django.db import migrations

from activities.models import RepeatOptions


def populate_repeat_options(apps, schema_editor):
    data = [
        {
            "name": "No Repeat"
        }, {
            "name": "Daily"
        }, {
            "name": "Weekly"
        }, {
            "name": "Monthly"
        }, {
            "name": "Yearly"
        }, {
            "name": "Weekdays"
        }, {
            "name": "Weekends"
        }
    ]

    for option in data:
        try:
            new_option = RepeatOptions.objects.create(**option)
        except Exception:
            print(option)
            continue


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0001_initial')
    ]

    operations = [
        migrations.RunPython(populate_repeat_options)
    ]
