# Generated by Django 2.1.1 on 2018-09-30 01:52
import json
from django.db import migrations, models

from activities.models import AgeRange


def populate_age_ranges(apps, schema_editor):
    age_ranges = [
        {
            'label': 'Kids',
            'min_age': 0,
            'max_age': 11
        }, {
            'label': 'Teens',
            'min_age': 12,
            'max_age': 17
        }, {
            'label': 'Young Adults',
            'min_age': 18,
            'max_age': 21
        }, {
            'label': 'Adults',
            'min_age': 22,
            'max_age': 64
        }, {
            'label': 'Seniors',
            'min_age': 65,
            'max_age': 120
        }
    ]

    for age_range in age_ranges:
        new_age_range = AgeRange(**age_range)
        new_age_range.save()


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0004_auto_20181105_0250')
    ]

    operations = [
        migrations.RunPython(populate_age_ranges)
    ]
