# Generated by Django 2.1.2 on 2019-07-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_feedback_responded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterModelOptions(
            name='feedbackcategory',
            options={'verbose_name_plural': 'Feedback Categories'},
        ),
    ]
