# Generated by Django 2.1.2 on 2019-03-17 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_auto_20190303_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='user',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
