# Generated by Django 2.1.2 on 2019-06-12 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_auto_20190317_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
