# Generated by Django 2.1.2 on 2019-01-22 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', 'populate_report_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='activities.Activity'),
        ),
    ]
