# Generated by Django 2.1.2 on 2019-07-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190528_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='reportcategory',
            options={'verbose_name_plural': 'Report Categories'},
        ),
        migrations.AddField(
            model_name='report',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
