# Generated by Django 2.1.2 on 2018-10-31 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_auto_20181028_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
